2025-09-10 23:57:24,856 DEBUG    root            Loaded Command Group: ['gcloud', 'resource_manager']
2025-09-10 23:57:24,857 DEBUG    root            Loaded Command Group: ['gcloud', 'resource-manager', 'org_policies']
2025-09-10 23:57:24,858 DEBUG    root            Loaded Command Group: ['gcloud', 'resource-manager', 'org-policies', 'set_policy']
2025-09-10 23:57:24,859 DEBUG    root            Running [gcloud.resource-manager.org-policies.set-policy] with arguments: [--organization: "985698468107", POLICY_FILE: "/tmp/domain-policy.yaml"]
2025-09-10 23:57:24,871 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2025-09-10 23:57:25,907 DEBUG    urllib3.connectionpool https://cloudresourcemanager.googleapis.com:443 "POST /v1/organizations/985698468107:setOrgPolicy?alt=json HTTP/11" 403 None
2025-09-10 23:57:25,910 DEBUG    root            (gcloud.resource-manager.org-policies.set-policy) [hanudani@gmail.com] does not have permission to access organizations instance [985698468107:setOrgPolicy] (or it may not exist): The caller does not have permission. This command is authenticated as hanudani@gmail.com which is the active account specified by the [core/account] property
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/gcloud-cli/538.0.0/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/gcloud-cli/538.0.0/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 946, in Run
    resources = command_instance.Run(args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/gcloud-cli/538.0.0/google-cloud-sdk/lib/surface/resource_manager/org_policies/set_policy.py", line 71, in Run
    return service.SetOrgPolicy(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/gcloud-cli/538.0.0/google-cloud-sdk/lib/googlecloudsdk/generated_clients/apis/cloudresourcemanager/v1/cloudresourcemanager_v1_client.py", line 618, in SetOrgPolicy
    return self._RunMethod(
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/gcloud-cli/538.0.0/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 747, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/gcloud-cli/538.0.0/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 753, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/gcloud-cli/538.0.0/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 612, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
apitools.base.py.exceptions.HttpForbiddenError: HttpError accessing <https://cloudresourcemanager.googleapis.com/v1/organizations/985698468107:setOrgPolicy?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Wed, 10 Sep 2025 20:57:25 GMT', 'server': 'ESF', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'server-timing': 'gfet4t7; dur=940', 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'transfer-encoding': 'chunked', 'status': 403}>, content <{
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}
>
2025-09-10 23:57:25,913 ERROR    root            (gcloud.resource-manager.org-policies.set-policy) [hanudani@gmail.com] does not have permission to access organizations instance [985698468107:setOrgPolicy] (or it may not exist): The caller does not have permission. This command is authenticated as hanudani@gmail.com which is the active account specified by the [core/account] property
