2025-09-16 00:24:48,402 DEBUG    root            Loaded Command Group: ['gcloud', 'resource_manager']
2025-09-16 00:24:48,407 DEBUG    root            Loaded Command Group: ['gcloud', 'resource-manager', 'folders']
2025-09-16 00:24:48,411 DEBUG    root            Loaded Command Group: ['gcloud', 'resource-manager', 'folders', 'get_iam_policy']
2025-09-16 00:24:48,412 DEBUG    root            Running [gcloud.resource-manager.folders.get-iam-policy] with arguments: [FOLDER_ID: "983073065"]
2025-09-16 00:24:48,424 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2025-09-16 00:24:49,693 DEBUG    urllib3.connectionpool https://cloudresourcemanager.googleapis.com:443 "POST /v2/folders/983073065:getIamPolicy?alt=json HTTP/11" 403 None
2025-09-16 00:24:49,697 DEBUG    root            (gcloud.resource-manager.folders.get-iam-policy) [hanudani@gmail.com] does not have permission to access folders instance [983073065:getIamPolicy] (or it may not exist): The caller does not have permission. This command is authenticated as hanudani@gmail.com which is the active account specified by the [core/account] property
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/gcloud-cli/538.0.0/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/gcloud-cli/538.0.0/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 946, in Run
    resources = command_instance.Run(args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/gcloud-cli/538.0.0/google-cloud-sdk/lib/surface/resource_manager/folders/get_iam_policy.py", line 46, in Run
    return folders.GetIamPolicy(args.id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/gcloud-cli/538.0.0/google-cloud-sdk/lib/googlecloudsdk/api_lib/resource_manager/folders.py", line 72, in GetIamPolicy
    return FoldersService().GetIamPolicy(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/gcloud-cli/538.0.0/google-cloud-sdk/lib/googlecloudsdk/generated_clients/apis/cloudresourcemanager/v2/cloudresourcemanager_v2_client.py", line 184, in GetIamPolicy
    return self._RunMethod(
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/gcloud-cli/538.0.0/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 747, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/gcloud-cli/538.0.0/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 753, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/gcloud-cli/538.0.0/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 612, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
apitools.base.py.exceptions.HttpForbiddenError: HttpError accessing <https://cloudresourcemanager.googleapis.com/v2/folders/983073065:getIamPolicy?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Mon, 15 Sep 2025 21:24:49 GMT', 'server': 'ESF', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'server-timing': 'gfet4t7; dur=1105', 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'transfer-encoding': 'chunked', 'status': 403}>, content <{
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}
>
2025-09-16 00:24:49,701 ERROR    root            (gcloud.resource-manager.folders.get-iam-policy) [hanudani@gmail.com] does not have permission to access folders instance [983073065:getIamPolicy] (or it may not exist): The caller does not have permission. This command is authenticated as hanudani@gmail.com which is the active account specified by the [core/account] property
